"""test

Revision ID: 1c61208f78a9
Revises: 
Create Date: 2025-10-03 12:18:22.314916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c61208f78a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('callsheet_view')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callsheet_view',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('callsheet_id', sa.INTEGER(), nullable=False),
    sa.Column('last_viewed_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['callsheet_id'], ['callsheet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'callsheet_id')
    )
    # ### end Alembic commands ###
