"""updated clearance table

Revision ID: 7f4a8731d6e8
Revises: e36f33b62b7f
Create Date: 2025-10-07 21:50:30.523291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f4a8731d6e8'
down_revision = 'e36f33b62b7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clearance_stock', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qty_sold', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clearance_stock', schema=None) as batch_op:
        batch_op.drop_column('qty_sold')

    # ### end Alembic commands ###
