"""updated address form

Revision ID: 8f7ea955b51e
Revises: 2ca23d6a1148
Create Date: 2025-10-05 14:45:08.401479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7ea955b51e'
down_revision = '2ca23d6a1148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.drop_column('state')
        batch_op.drop_column('country')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
