"""customer addresses

Revision ID: 90f4b3705d5c
Revises: 1c61208f78a9
Create Date: 2025-10-03 14:17:12.413712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f4b3705d5c'
down_revision = '1c61208f78a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_premise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('contact_name')
        batch_op.drop_column('email')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('contact_name', sa.VARCHAR(length=100), nullable=True))

    op.drop_table('customer_premise')
    # ### end Alembic commands ###
