"""addresses yet again...

Revision ID: 94462c5234c5
Revises: 8f7ea955b51e
Create Date: 2025-10-05 15:12:36.951165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94462c5234c5'
down_revision = '8f7ea955b51e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('callsheet_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('address_label', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_callsheet_entry_address', 'customer_address', ['address_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('callsheet_entry', schema=None) as batch_op:
        batch_op.drop_constraint('fk_callsheet_entry_address', type_='foreignkey')
        batch_op.drop_column('address_label')
        batch_op.drop_column('address_id')

    # ### end Alembic commands ###
