"""add database indexs for performance

Revision ID: c52b6c07bc76
Revises: 94462c5234c5
Create Date: 2025-10-05 20:07:14.580805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c52b6c07bc76'
down_revision = '94462c5234c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('callsheet_entry', schema=None) as batch_op:
        batch_op.create_index('idx_callsheet_position', ['callsheet_id', 'position'], unique=False)
        batch_op.create_index('idx_callsheet_status', ['callsheet_id', 'is_paused'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index('idx_customer_account', ['account_number'], unique=False)
        batch_op.create_index('idx_customer_name', ['name'], unique=False)

    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.create_index('idx_form_status', ['is_completed', 'is_archived'], unique=False)
        batch_op.create_index('idx_form_type', ['type'], unique=False)
        batch_op.create_index('idx_form_user_date', ['user_id', 'date_created'], unique=False)

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('idx_product_code', ['code'], unique=False)
        batch_op.create_index('idx_product_name', ['name'], unique=False)

    with op.batch_alter_table('standing_order_schedule', schema=None) as batch_op:
        batch_op.create_index('idx_schedule_date_status', ['scheduled_date', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('standing_order_schedule', schema=None) as batch_op:
        batch_op.drop_index('idx_schedule_date_status')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index('idx_product_name')
        batch_op.drop_index('idx_product_code')

    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_index('idx_form_user_date')
        batch_op.drop_index('idx_form_type')
        batch_op.drop_index('idx_form_status')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index('idx_customer_name')
        batch_op.drop_index('idx_customer_account')

    with op.batch_alter_table('callsheet_entry', schema=None) as batch_op:
        batch_op.drop_index('idx_callsheet_status')
        batch_op.drop_index('idx_callsheet_position')

    # ### end Alembic commands ###
