"""Add CallHistory table for call tracking and analytics

Revision ID: d5a93e6c8f38
Revises: 7f4a8731d6e8
Create Date: 2025-10-11 22:05:41.134620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5a93e6c8f38'
down_revision = '7f4a8731d6e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('callsheet_id', sa.Integer(), nullable=True),
    sa.Column('call_date', sa.DateTime(), nullable=False),
    sa.Column('call_status', sa.String(length=20), nullable=False),
    sa.Column('called_by', sa.Integer(), nullable=False),
    sa.Column('person_spoken_to', sa.String(length=100), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['called_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['callsheet_id'], ['callsheet.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_history', schema=None) as batch_op:
        batch_op.create_index('idx_call_history_customer_date', ['customer_id', 'call_date'], unique=False)
        batch_op.create_index('idx_call_history_status', ['call_status'], unique=False)
        batch_op.create_index('idx_call_history_week', ['year', 'week_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_history_call_date'), ['call_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_history_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_history_week_number'), ['week_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_call_history_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_history_year'))
        batch_op.drop_index(batch_op.f('ix_call_history_week_number'))
        batch_op.drop_index(batch_op.f('ix_call_history_customer_id'))
        batch_op.drop_index(batch_op.f('ix_call_history_call_date'))
        batch_op.drop_index('idx_call_history_week')
        batch_op.drop_index('idx_call_history_status')
        batch_op.drop_index('idx_call_history_customer_date')

    op.drop_table('call_history')
    # ### end Alembic commands ###
