"""clearnace stock added

Revision ID: e36f33b62b7f
Revises: cf555c115693
Create Date: 2025-10-07 21:32:19.809927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36f33b62b7f'
down_revision = 'cf555c115693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clearance_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=50), nullable=False),
    sa.Column('his_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('supplier_link', sa.String(length=500), nullable=True),
    sa.Column('pallet', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clearance_stock', schema=None) as batch_op:
        batch_op.create_index('idx_clearance_his_code', ['his_code'], unique=False)
        batch_op.create_index('idx_clearance_pallet', ['pallet'], unique=False)
        batch_op.create_index('idx_clearance_supplier_code', ['supplier_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clearance_stock', schema=None) as batch_op:
        batch_op.drop_index('idx_clearance_supplier_code')
        batch_op.drop_index('idx_clearance_pallet')
        batch_op.drop_index('idx_clearance_his_code')

    op.drop_table('clearance_stock')
    # ### end Alembic commands ###
